sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: FfdJ90VWKPDcoQv93L3SZ0DlXDLebQ0bF5dFj1Yjc6QCl9wc02B04yr/QCCbKKbT6PiRRteSiL7gdPpYH891iKOn6/6q9WaIxdH6yZzAPpDhgKpFtFVW1BS8GUoh+MWZXcXv7ggRVGDFdOLer5/xH2ei87FXisOnjyUuZdaLnP7qYJiharxD/vHTAMnPOAQ2H6trqhXYCS+mfCvaDYLVdoILlKbkQP5eVDvNmlmbBlY1mBDsT0JLs5+Wj7HkwBlo1R7OMgRQM5mmL9TaJ8KEhS/hb11ddQMkEdHCbS4GmO3NI7+8sALLQbddyqY9a4RlZYjcViz8f2gFQAsX4NG0ATD00vWHQlCvzIhJnC3OkB9J7l4h+rkwrWfodur0e1OshKOyuRe/6hKDYskPNb4lCtX10XThnwPssnFQL+fbD+Nfdje/6tl3M3JBXSpbd6YpM2RbSF8P595va/EEZIfusuT21shRavvETMrKpNaAx1fvPxJuD4+WHXYJOMkaK7JfnXCJvW/tLXvW0OBEU7iJCAxlpSQRr5rfW+y45l6Gnj4Vf2kdtfXnSo+G0/Zkbv5kYhmB1AKtW6tsCErVVAUmsks0gIQIjnYTS4Zmvf/ZrvNJbzfygs1KqzXAIcUxdhI2m/3gAlpOxhPd0Lp9JlG3H7d3MGc9C0yMHvUWPAH7Tb0=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Conflict_433
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy